### ISSUE TITLE
Compilation errors in stb_image on iOS

### ISSUE THREAD

**Issue by dri-richard** [britzl/extension-imgui#12]
WARNING: imgui/src/imgui/stb_image.h(592): expanded from macro 'STBI_THREAD_LOCAL'
ERROR: imgui/src/imgui/stb_image.h:1070: 'thread-local storage is not supported for the current target'
      #define STBI_THREAD_LOCAL       thread_local

**Comment by britzl** [comment]
Yep, the extension is currently untested on iOS

**Comment by dri-richard** [comment]
I should have been clearer - I saw the support was 'unknown' on iOS but I thought it possible that it might work.

**Comment by britzl** [comment]
> I should have been clearer - I saw the support was 'unknown' on iOS but I thought it possible that it might work.

Got it! I think it's possible to fix the issue and make it run on iOS as well.

**Comment by britzl** [comment]
I'm actually not getting any build errors on 1.2.185 (where we updated the iOS SDK version). Closing.

**Comment by dri-richard** [comment]
I see the same issues with 1.2.185.

Building the example project - this is on my Windows PC, but I see the same results on our game project with a Github Actions MacOS runner.

`D:\User Documents\Richard\Defold projects\extension-imgui-master>java -jar d:\Installs\Defold_1.2.185\bob.jar --platform armv7-darwin --verbose resolve distclean build --archive bundle`

produces:

```The build failed for the following reasons:

ERROR: imgui/src/imgui/stb_image.h:931: 'thread-local storage is not supported for the current target
STBI_THREAD_LOCAL'

INFO: imgui/src/imgui/stb_image.h:592: 'expanded from macro 'STBI_THREAD_LOCAL'
      #define STBI_THREAD_LOCAL       thread_local'

ERROR: imgui/src/imgui/stb_image.h:1070: 'thread-local storage is not supported for the current target
static STBI_THREAD_LOCAL int stbi__vertically_flip_on_load_local, stbi__vertically_flip_on_load_set;'

INFO: imgui/src/imgui/stb_image.h:592: 'expanded from macro 'STBI_THREAD_LOCAL'
      #define STBI_THREAD_LOCAL       thread_local'

ERROR: imgui/src/imgui/stb_image.h:1070: 'thread-local storage is not supported for the current target'

INFO: imgui/src/imgui/stb_image.h:592: 'expanded from macro 'STBI_THREAD_LOCAL'
      #define STBI_THREAD_LOCAL       thread_local'```

**Comment by dri-richard** [comment]
Well... I can get it to build by removing 32bit support, but that's not the default.

**Comment by britzl** [comment]
We will remove 32-bit as the iOS devices with 32-bit architecture actually do not support OpenGL3 (which we migrated to recently). We have refrained from removing 32-bit support as it would impact updates to already released iOS games.
