### ISSUE TITLE
Build error in Defold 1.2.186

### ISSUE THREAD

**Issue by 8bitskull** [britzl/extension-imgui#14]
Build Errors when building in Windows 10. I don’t actually use imgui in this project, I just have it fetched as a dependency.

```
/imgui/ext.manifest
	clang-10: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
	lld-link: error: undefined symbol: __cpuid
```

```
>>> referenced by /tmp/job5884567677308494677/upload/imgui/src/imgui/stb_image.h:1091
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void * __cdecl stbi__load_main(struct stbi__context *, int *, int *, int *, int, struct stbi__result_info *, int))
>>> referenced by /tmp/job5884567677308494677/upload/imgui/src/imgui/stb_image.h:1091
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void * __cdecl stbi__load_main(struct stbi__context *, int *, int *, int *, int, struct stbi__result_info *, int))
	lld-link: error: undefined symbol: _mm_setr_epi16
>>> referenced by /tmp/job5884567677308494677/upload/imgui/src/imgui/stb_image.h:2541
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job5884567677308494677/upload/imgui/src/imgui/stb_image.h:2542
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job5884567677308494677/upload/imgui/src/imgui/stb_image.h:2543
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job5884567677308494677/upload/imgui/src/imgui/stb_image.h:2544
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job5884567677308494677/upload/imgui/src/imgui/stb_image.h:2545
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job5884567677308494677/upload/imgui/src/imgui/stb_image.h:2546
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job5884567677308494677/upload/imgui/src/imgui/stb_image.h:2547
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job5884567677308494677/upload/imgui/src/imgui/stb_image.h:2548
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
	lld-link: error: undefined symbol: _mm_set1_epi32
>>> referenced by /tmp/job5884567677308494677/upload/imgui/src/imgui/stb_image.h:2551
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job5884567677308494677/upload/imgui/src/imgui/stb_image.h:2552
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
	lld-link: error: undefined symbol: _mm_load_si128
>>> referenced by /tmp/job5884567677308494677/upload/imgui/src/imgui/stb_image.h:2555
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job5884567677308494677/upload/imgui/src/imgui/stb_image.h:2556
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))


(etc)
```

**Comment by britzl** [comment]
https://www.sizeofvoid.com/2018/12/02/get-the-default-include-paths-from-clang/

**Comment by britzl** [comment]
Closed by https://github.com/britzl/extension-imgui/pull/19

**Comment by 8bitskull** [comment]
I've fetched the latest version of this repo and I'm still getting issues in 1.2.187. Builds fine in 1.2.184. Have I missed something or is the issue still active?

`clang-10: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]`

`lld-link: error: undefined symbol: __cpuid
>>> referenced by /tmp/job8480497724863692534/upload/imgui/src/stb/stb_image.h:1148
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void * __cdecl stbi__load_main(struct stbi__context *, int *, int *, int *, int, struct stbi__result_info *, int))
>>> referenced by /tmp/job8480497724863692534/upload/imgui/src/stb/stb_image.h:1148
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void * __cdecl stbi__load_main(struct stbi__context *, int *, int *, int *, int, struct stbi__result_info *, int))`

`lld-link: error: undefined symbol: _mm_setr_epi16
>>> referenced by /tmp/job8480497724863692534/upload/imgui/src/stb/stb_image.h:2581
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job8480497724863692534/upload/imgui/src/stb/stb_image.h:2582
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job8480497724863692534/upload/imgui/src/stb/stb_image.h:2583
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job8480497724863692534/upload/imgui/src/stb/stb_image.h:2584
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job8480497724863692534/upload/imgui/src/stb/stb_image.h:2585
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job8480497724863692534/upload/imgui/src/stb/stb_image.h:2586
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job8480497724863692534/upload/imgui/src/stb/stb_image.h:2587
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))
>>> referenced by /tmp/job8480497724863692534/upload/imgui/src/stb/stb_image.h:2588
>>>               DefoldImGui_1.lib(extension_imgui.cpp_0.o):(void __cdecl stbi__idct_simd(unsigned char *, int, short *const))`

etc etc

**Comment by britzl** [comment]
Excellent! Closing the issue.
