### ISSUE TITLE
 /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found 

### ISSUE THREAD

**Issue by dlannan** [britzl/extension-imgui#25]
Im getting this error when trying to build imgui now.  Im not sure if its because Ive updated Defold or if there are build issues with extensions? I think this is related to new Defold. Might try an old one, and see if there are issues.

Any help would be great. 
System: Debian 10 dual Intel Xeon 2.5GHz lots of ram.

**Comment by britzl** [comment]
We did some updates to the build server recently and upgraded from Ubuntu 16 to 20:

https://github.com/defold/extender/commit/9d794d980d83b67f6f9257313d8cbc9c8d8a4b7c#diff-9e21e98960ace690e6b03735796e234feba760f01718304e9e51d269151c65a8R1

**Comment by dlannan** [comment]
Yes. I saw that in the discord discussions. Thanks. I think I have it sorted - its building. I migrated to Debian 11 which appears to be all happy :) .. closing.
