### ISSUE TITLE
Error when building for HTML5 (1.6.4)

### ISSUE THREAD

**Issue by Laminariy** [britzl/extension-imgui#43]
Release Version: 1.3.2 (latest)
Engine version: 1.6.4
Build Log:
[log.txt](https://github.com/britzl/extension-imgui/files/14294179/log.txt)

Upd: main branch builds fine

**Comment by britzl** [comment]
I'm able to build the extension for html5 using 1.6.4.



> Upd: main branch builds fine

What does this mean? Is it working for you or not?

**Comment by SalavatR** [comment]
@britzl 
last release on commit 32bc917,  
https://github.com/britzl/extension-imgui/archive/refs/tags/1.3.2.zip this does not work

https://github.com/britzl/extension-imgui/archive/refs/heads/master.zip works fine
