### ISSUE TITLE
[Feature Request] Support cyrillic and other glyphs in text/input_text

### ISSUE THREAD

**Issue by S0Close** [britzl/extension-imgui#56]
1. To display non-ascii symbols it should be possible to specify glyphs range in imgui_FontAddTTFFile (at least predefined ranges). AddFontFromFileTTF supports 4th parameter for that, for example: io.Fonts->AddFontFromFileTTF("font.ttf", size_pixels, nullptr, io.Fonts->GetGlyphRangesCyrillic());
2. For input_text it is required to support ImGuiIO::AddInputCharactersUTF8 (and probably ImGuiIO::AddInputCharacterUTF16 for some languages, i checked only UTF8 method for cyrillic)
3. (optional) It would be handy to implement ImGui::DebugTextEncoding method to check characters encoding

**Comment by britzl** [comment]
Added: https://github.com/britzl/extension-imgui/releases/tag/2.3.0
