### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by 8bitskull** [britzl/extension-imgui#9]
I would love to see the progress bar functionality from the demo!

![image](https://user-images.githubusercontent.com/24439991/122207960-a0068780-ce9a-11eb-9c93-c61316f2f14e.png)

I think this is the relevant section of the demo in the main imgui repo:
https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp#L1626

**Comment by dlannan** [comment]
Will add. I'll send a PR to britzl in a bit.

**Comment by britzl** [comment]
Closed by #11
